/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsi9;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Rayhan Faridh
 */
public class EntryPanel extends javax.swing.JPanel {

  /**
   * Creates new form EntryPanel
   */
  public EntryPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jkBtnGroup = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    lakiRadioButton = new javax.swing.JRadioButton();
    membacaCheckbox = new javax.swing.JCheckBox();
    perempuanRadioButton = new javax.swing.JRadioButton();
    menyanyiCheckbox = new javax.swing.JCheckBox();
    jLabel4 = new javax.swing.JLabel();
    berenangCheckbox = new javax.swing.JCheckBox();
    umurSpinner = new javax.swing.JSpinner();
    simpanButton = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    alamatTextArea = new javax.swing.JTextArea();
    nimTextField = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    namaTextField = new javax.swing.JTextField();
    provinsiComboBox = new javax.swing.JComboBox<>();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    mahasiswaTable = new javax.swing.JTable();

    jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize() + 2f));
    jLabel3.setText("Jenis Kelamin:");

    jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
    jLabel8.setText("Hobi:");

    jkBtnGroup.add(lakiRadioButton);
    lakiRadioButton.setText("Laki-laki");
    lakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lakiRadioButtonActionPerformed(evt);
      }
    });

    membacaCheckbox.setText("Membaca");

    jkBtnGroup.add(perempuanRadioButton);
    perempuanRadioButton.setText("Perempuan");
    perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        perempuanRadioButtonActionPerformed(evt);
      }
    });

    menyanyiCheckbox.setText("Menyanyi");

    jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
    jLabel4.setText("Umur:");

    berenangCheckbox.setText("Berenang");

    umurSpinner.setModel(new javax.swing.SpinnerNumberModel(15, 10, 60, 1));

    simpanButton.setText("Simpan");
    simpanButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        simpanButtonActionPerformed(evt);
      }
    });

    jLabel5.setText("tahun");

    jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
    jLabel6.setText("Alamat:");

    jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
    jLabel1.setText("NIM:");

    alamatTextArea.setColumns(20);
    alamatTextArea.setRows(5);
    jScrollPane1.setViewportView(alamatTextArea);

    jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
    jLabel2.setText("Nama:");

    jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
    jLabel7.setText("Provinsi:");

    provinsiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] { "Aceh", "DKI Jakarta", "Jawa Timur", "Bali", "Maluku", "Papua" }));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perempuanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lakiRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(umurSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 83,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(provinsiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(membacaCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menyanyiCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(berenangCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(simpanButton, javax.swing.GroupLayout.Alignment.TRAILING,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lakiRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perempuanRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umurSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(85, 85, 85)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(provinsiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(membacaCheckbox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menyanyiCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(berenangCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpanButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    mahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {

        },
        new String[] {
            "NIM", "Nama", "Jenis Kelamin", "Umur"
        }) {
      Class[] types = new Class[] {
          java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
      };
      boolean[] canEdit = new boolean[] {
          false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types[columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit[columnIndex];
      }
    });
    jScrollPane2.setViewportView(mahasiswaTable);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
  }// </editor-fold>//GEN-END:initComponents

  private void lakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_lakiRadioButtonActionPerformed
    if (perempuanRadioButton.isSelected()) {
      perempuanRadioButton.setSelected(false);
    }
  }// GEN-LAST:event_lakiRadioButtonActionPerformed

  private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_perempuanRadioButtonActionPerformed
    if (lakiRadioButton.isSelected()) {
      lakiRadioButton.setSelected(false);
    }
  }// GEN-LAST:event_perempuanRadioButtonActionPerformed

  private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_simpanButtonActionPerformed
    Mahasiswa mhs = new Mahasiswa();
    mhs.setNim(nimTextField.getText());
    mhs.setNama(namaTextField.getText());

    if (lakiRadioButton.isSelected()) {
      mhs.setJenisKelamin("Laki-laki");
    } else if (perempuanRadioButton.isSelected()) {
      mhs.setJenisKelamin("Perempuan");
    }

    int umur = (Integer) umurSpinner.getValue();
    mhs.setUmur(umur);

    mhs.setAlamat(alamatTextArea.getText());
    mhs.setProvinsi(provinsiComboBox.getSelectedItem().toString());

    ArrayList<String> hobiList = new ArrayList<>();
    if (membacaCheckbox.isSelected()) {
      hobiList.add("membaca");
    }

    if (menyanyiCheckbox.isSelected()) {
      hobiList.add("menyanyi");
    }

    if (berenangCheckbox.isSelected()) {
      hobiList.add("berenang");
    }

    mhs.setHobi(hobiList);
    Database.getInstance().insertMahasiswa(mhs);

    clearForm();
    JOptionPane.showMessageDialog(this, "Sukses tersimpan");
    loadTableData();
  }// GEN-LAST:event_simpanButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea alamatTextArea;
  private javax.swing.JCheckBox berenangCheckbox;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.ButtonGroup jkBtnGroup;
  private javax.swing.JRadioButton lakiRadioButton;
  private javax.swing.JTable mahasiswaTable;
  private javax.swing.JCheckBox membacaCheckbox;
  private javax.swing.JCheckBox menyanyiCheckbox;
  private javax.swing.JTextField namaTextField;
  private javax.swing.JTextField nimTextField;
  private javax.swing.JRadioButton perempuanRadioButton;
  private javax.swing.JComboBox<String> provinsiComboBox;
  private javax.swing.JButton simpanButton;
  private javax.swing.JSpinner umurSpinner;
  // End of variables declaration//GEN-END:variables

  private void loadTableData() {
    DefaultTableModel dtm = (DefaultTableModel) mahasiswaTable.getModel();

    while (dtm.getRowCount() > 0) {
      dtm.removeRow(0);
    }

    for (Mahasiswa mhs : Database.getInstance().getListMahasiswa()) {
      dtm.addRow(new Object[] {
          mhs.getNim(),
          mhs.getNama(),
          mhs.getJenisKelamin(),
          mhs.getUmur()
      });
    }
  }

  private void clearForm() {
    nimTextField.setText("");
    namaTextField.setText("");
    jkBtnGroup.clearSelection();
    umurSpinner.setValue(15);
    alamatTextArea.setText("");
    provinsiComboBox.setSelectedIndex(-1);
    membacaCheckbox.setSelected(false);
    menyanyiCheckbox.setSelected(false);
    berenangCheckbox.setSelected(false);
  }
}
