/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsi9;

import javax.swing.JScrollPane;

/**
 *
 * @author Muhammad Rayhan Faridh
 */
public class LoginPanel extends javax.swing.JPanel {
  private final JScrollPane contentScrollPane;

  /**
   * Creates new form LoginPanel
   */
  public LoginPanel(JScrollPane contentScrollPane) {
    initComponents();
    this.contentScrollPane = contentScrollPane;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel1 = new javax.swing.JLabel();
    usernameField = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    passwordField = new javax.swing.JPasswordField();
    loginButton = new javax.swing.JButton();

    setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Username:");
    jLabel1.setPreferredSize(new java.awt.Dimension(80, 16));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    add(jLabel1, gridBagConstraints);

    usernameField.setPreferredSize(new java.awt.Dimension(150, 28));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    add(usernameField, gridBagConstraints);

    jLabel2.setText("Password:");
    jLabel2.setPreferredSize(new java.awt.Dimension(80, 16));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    add(jLabel2, gridBagConstraints);

    passwordField.setPreferredSize(new java.awt.Dimension(150, 28));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    add(passwordField, gridBagConstraints);

    loginButton.setText("LOGIN");
    loginButton.setPreferredSize(new java.awt.Dimension(80, 28));
    loginButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loginButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
    gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
    add(loginButton, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginButtonActionPerformed
    contentScrollPane.setViewportView(new HomePanel());
  }// GEN-LAST:event_loginButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JButton loginButton;
  private javax.swing.JPasswordField passwordField;
  private javax.swing.JTextField usernameField;
  // End of variables declaration//GEN-END:variables
}
